<!DOCTYPE html>
<html>
<body>
    <h1>Modelos</h1>
    
    <p>
	   <a class="btn btn-success"
		href="<?=$this->basePath("login/user/cerrar")?>">Cerrar sesión</a>
   </p>
    
    <?php 
    $flash=$this->flashMessenger()
                ->setMessageOpenFormat('<div%s>')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>');
    
                
                //echo "<pre>"; print_r($this->modelos); exit;
                
    ?>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Descripción</th>
            <th>Imagen</th>
            <th>Nombre</th>
            <th>Fecha</th>
            <th>Hora</th>
            <th>Donde se tomo</th>
        </tr>
        <?php foreach($this->modelos as $modelo){ ?>
        <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
        
        <?php
            //echo "<pre>"; print_r($modelo); 
        ?>
        
            <td><?php echo $modelo["id"]?></td>
            <td><?php echo $modelo["descripcion"]?></td>       
            <td> <img src="<?php echo $modelo["imagen"]?>" height="100px" width="50px" alt="Italian Trulli"></td> 
            <td><?php echo $modelo["nombre"]?></td>
            <td><?php echo $modelo["fecha"] ;?></td>
            <td><?php echo $modelo["hora"] ;?></td>
            <td>
            	<button type="button" class="btn btn-primary" onclick="imprimir(this)" data-toggle="modal" data-target="#exampleModal" >Mostrar mapa</button>
            </td>
            <td style="display:none;"><?php echo $modelo["latitud"] ;?></td>
            <td style="display:none;"><?php echo $modelo["longitud"] ;?></td>
        </tr>
        <?php } ?>
    </table>


	<!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Mapa de donde se tomo la foto</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
          
          
          
          
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
      
      <script type="text/javascript">

      var id;
      var latitud;
      var longitud;

      
      $('#exampleModal').on('show.bs.modal', function (event) {
    	  var modal = $(this);
    	  //con esta linea de codigo se agrega el html
    	  modal.find('.modal-body').append("<img src='https://www.chiquipedia.com/imagenes/imagenes-animo09.jpg' height='100%' width='50%' alt='Italian Trulli'>");
    	  //con esta linea de codigo se agrega texto
    	  modal.find('.modal-body').text("latitud  ===> " + latitud + "   longitud ===> " + longitud);
    	})
    	
    	function imprimir(boton){
      	
        	var celdas = $(boton).closest('tr').find('td');
        	id = celdas.eq(0).text();
        	latitud = celdas.eq(7).text();
        	longitud = celdas.eq(8).text();
        	
     	}
      </script>
</html>
