<style>
body, .modal-open .page-container, .modal-open .page-container .navbar-fixed-top, .modal-open .modal-container {
    overflow-y: scroll;
}
@media (max-width: 979px) {
    .modal-open .page-container .navbar-fixed-top {
        overflow-y: visible;
    }
}
#map-canvas {
    height: 400px;
}
</style>
<div id="map-canvas"></div>


<div class="page-container">
    <div class="container">
        <br />
        <button class="btn launch-map">Launch Map</button>
    </div>
</div>
<div id="modal" class="modal hide fade">
    <div class="modal-body">
        
    </div>
    <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn btn-primary" data-value="1">Continue</button>
        <button type="button" data-dismiss="modal" class="btn" data-value="0">Cancel</button>
    </div>
</div>
	
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>

 var center = new google.maps.LatLng(43.5293,-5.6773);

console.log("entra");
function initialize() {

	console.log("entra");
    var mapOptions = {
        zoom: 20,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: center
    };

    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    var marker = new google.maps.Marker({
        map: map,
        position: center
    });
}

$('.launch-map').on('click', function () {
    
    $('#modal').modal({
        backdrop: 'static',
        keyboard: false
    }).on('shown.bs.modal', function () {
        google.maps.event.trigger(map, 'resize');
        map.setCenter(center);
    });
});

initialize();
</script>

