<style>
body, .modal-open .page-container, .modal-open .page-container .navbar-fixed-top,
	.modal-open .modal-container {
	overflow-y: scroll;
}

@media ( max-width : 979px) {
	.modal-open .page-container .navbar-fixed-top {
		overflow-y: visible;
	}
}

#map-canvas {
	height: 400px;
}
</style>


<button type="button" class="btn btn-primary"
					data-toggle="modal"
					data-target="#exampleModal">Launch Map</button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
	aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Mapa de donde se tomo
					la foto</h5>
				
<!-- 				<button type="button" class="close" data-dismiss="modal" aria-label="Close"> -->
<!-- 					<span aria-hidden="true">&times;</span> -->
<!-- 				</button> -->
			</div>
			<div class="modal-body">
			<div id="map-canvas"></div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>

</div>



<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>

 var center = new google.maps.LatLng(43.5293,-5.6773);

console.log("entra");
function initialize() {

	console.log("entra");
    var mapOptions = {
        zoom: 20,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: center
    };

    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    var marker = new google.maps.Marker({
        map: map,
        position: center
    });
}

$('#exampleModal').on('show.bs.modal', function () {
    
	var modal = $(this);
});

initialize();
</script>

